### ISSUE TITLE
add additional simpler CD layout

### ISSUE THREAD

**Issue by ggzengel** [crobinso/virtio-win-pkg-scripts#27]
I hope this is the right place for this issue.
A while back I opened this issue here: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/157

**Comment by crobinso** [comment]
Yes it's the right place. The current iso layout does have some of the simpler layout, but not all drivers are available there. The reason is that the simpler layout is what windows installer uses to autodetect available drivers for the architecture. If we put every driver on the CD under that directory structure, using the iso at install time gives options for every driver multiple times over, rather than just the critical storage and network drivers that are already there. This was an explicit choice, see the discussion here: https://github.com/crobinso/virtio-win-pkg-scripts/pull/16

So I don't expect we will be changing this unless there's a stronger reason to do so
